# -*- coding: utf-8 -*-
"""tournament_sim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffXftqYzLmSsXqoJadWmIeDbOthcFM06
"""

import numpy as np
import matplotlib.pyplot as plt # Library for plotting graphs

# --- 1. SETUP ---
np.random.seed(42)
n_bots = 10
# Everyone starts at 1200
elo_ratings = np.ones(n_bots) * 1200
# Random "True Skills" (Hidden from the bots)
true_skills = np.sort(np.random.randint(10, 90, n_bots))
bot_names = [f"Bot_{i}" for i in range(n_bots)]

# To track history for the graph: [Game 0, Game 1, ...]
history = [elo_ratings.copy()]

# --- 2. THE ELO MATH ---
def get_expected_score(rating_a, rating_b):
    """
    The Logistic Curve: Probability that A beats B based on rating difference.
    """
    return 1 / (1 + 10**((rating_b - rating_a) / 400))

def update_elo(rating_a, rating_b, actual_score):
    """
    Updates ratings using the formula: R_new = R_old + K * (Actual - Expected)
    """
    K = 32 # How fast ratings change
    expected_a = get_expected_score(rating_a, rating_b)

    new_a = rating_a + K * (actual_score - expected_a)
    new_b = rating_b + K * ((1 - actual_score) - (1 - expected_a))
    return new_a, new_b

# --- 3. RUN TOURNAMENT ---
print("--- Simulating Tournament ---")
# We loop 5 times (5 seasons) to let ratings settle
for season in range(5):
    for i in range(n_bots):
        for j in range(i + 1, n_bots):
            # 1. Simulate the Game (Who actually wins?)
            diff = true_skills[i] - true_skills[j]
            prob_a = 1 / (1 + 10**(-diff / 400))
            winner_is_a = 1 if np.random.rand() < prob_a else 0

            # 2. Update Elo Ratings
            elo_ratings[i], elo_ratings[j] = update_elo(elo_ratings[i], elo_ratings[j], winner_is_a)

            # 3. Save snapshot for the graph
            history.append(elo_ratings.copy())

# --- 4. PRINT RESULTS ---
print("\n--- FINAL ELO RANKINGS ---")
sorted_indices = np.argsort(elo_ratings)[::-1] # Sort highest to lowest
for i in sorted_indices:
    print(f"{bot_names[i]}: {elo_ratings[i]:.0f} (True Skill: {true_skills[i]})")

# --- 5. GENERATE THE GRAPH ---
print("\nGenerating graph...")
history = np.array(history)
plt.figure(figsize=(10, 6))

# Plot lines for the top 3 and bottom 3 bots
for i in range(n_bots):
    plt.plot(history[:, i], label=bot_names[i])

plt.title("Elo Rating Convergence Over Time")
plt.xlabel("Games Played")
plt.ylabel("Elo Rating")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left') # Put legend outside
plt.tight_layout()

# Save the graph as an image file
plt.savefig("elo_graph.png")
print(" elo_graph.png")
plt.show()